name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()  # Condition: exécute ce job seulement si le job 'build' a réussi

    steps:
      - name: Deploy to production
        run: echo "Déploiement de l'application en production..."

  notify:
    runs-on: ubuntu-latest
    needs: build
    if: failure()  # Condition: exécute ce job seulement si le job 'build' a échoué

    steps:
      - name: Notify failure
        run: echo "Les tests ont échoué. Notification envoyée."
